name: flut_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  http: ^1.0.0
  json_annotation: ^4.8.1
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5
  equatable: ^2.0.3
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.4.10
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4
  mocktail: ^1.0.3
  mockito: ^5.4.4
  mocktail_image_network: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.7
  test: ^1.24.9
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
